In [18]:
## Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import sqlite3    ## SQL Interface
import pickle     ## Used to save your data - Converts objects to byte stream and vice versa

from sklearn.feature_extraction.text import CountVectorizer  ## BOW Model
from sklearn.feature_extraction.text import TfidfVectorizer  ## TFIDF Model

from sklearn.manifold import TSNE    ## To visualize high dimensional data

## Modules to perform Text Preprocessing
import re
import nltk

from nltk.corpus import stopwords
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from matplotlib.colors import ListedColormap
from sklearn.metrics import accuracy_score
%matplotlib inline


import gensim    ## To build Word2Vec model

## final.sqlite contains preprocessed data and is shuffled with random state =123

In [19]:
con=sqlite3.connect("saved_data//final.sqlite")
final=pd.read_sql_query("select * from Reviews",con)
con.close

<function Connection.close>

In [20]:
tfidf=TfidfVectorizer()
tfidf_vector=tfidf.fit_transform(final["CleanedText"].values)

# taking subset of first 2000 points

In [21]:
df1=final["Score"][200000:202000]

In [26]:
df1

200000    0
200001    1
200002    0
200003    1
200004    1
200005    1
200006    1
200007    1
200008    1
200009    0
200010    1
200011    1
200012    1
200013    1
200014    1
200015    1
200016    1
200017    1
200018    1
200019    1
200020    1
200021    1
200022    1
200023    1
200024    1
200025    1
200026    0
200027    1
200028    1
200029    1
         ..
201970    1
201971    1
201972    1
201973    1
201974    0
201975    1
201976    1
201977    0
201978    1
201979    1
201980    1
201981    1
201982    1
201983    1
201984    1
201985    1
201986    1
201987    1
201988    1
201989    1
201990    1
201991    1
201992    1
201993    1
201994    1
201995    1
201996    1
201997    0
201998    1
201999    1
Name: Score, Length: 2000, dtype: int64

In [22]:
df2=pd.DataFrame(tfidf_vector[200000:202000,:].toarray())

In [25]:
df2

0      1      2      3      4      5      6      7      8      9      \
0       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
6       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
8       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
11      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
12      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
13      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
14      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
15      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
16      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
17      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
18      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
19      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
20      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
21      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
22      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
23      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
24      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
25      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
26      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
27      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
28      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
29      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1970    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1971    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1972    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1973    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1974    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1975    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1976    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1977    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1978    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1979    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1980    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1981    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1982    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1983    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1984    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1985    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1986    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1987    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1988    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1989    0.0    0.0    0.0   

In [23]:
df=pd.concat([df1,df2],axis=1)

In [24]:
df

Score    0    1    2    3    4    5    6    7    8  ...    71681  \
0         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
1         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
2         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
3         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
4         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
5         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
6         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
7         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
8         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
9         NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
10        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
11        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
12        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
13        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
14        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
15        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
16        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
17        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
18        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
19        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
20        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
21        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
22        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
23        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
24        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
25        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
26        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
27        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
28        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
29        NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...   
201970    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201971    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201972    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201973    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201974    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201975    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201976    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201977    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201978    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201979    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201980    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201981    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201982    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201983    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201984    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201985    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201986    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201987    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201988    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201989    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN   
201990    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N

In [7]:
Y=df["Score"]

In [8]:
X=df.iloc[:,1:].values

In [9]:
s=StandardScaler()
X=s.fit_transform(X)

In [10]:
X.shape

(2000, 71691)

# splitting into test and train parts

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size = 0.3, random_state = 123)

In [ ]:
?KNeighborsClassifier

In [ ]:
?cross_val_score

### finding the optimal value of k

In [12]:
cv_scores=[]
neighbors=list(range(1,20,2))
for k in neighbors:
    knn=KNeighborsClassifier(n_neighbors=k,n_jobs=4)
    score=cross_val_score(knn,X_train,Y_train,cv=5,scoring="accuracy")
    print(score)
    cv_scores.append(score.mean())
    

[0.83985765 0.85       0.85357143 0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]
[0.84697509 0.85       0.85       0.85       0.84946237]


In [13]:
MSE=[1-x for x in cv_scores]

In [14]:
optimal_knn=neighbors[MSE.index(min(MSE))]
optimal_knn

3

### training the model

In [15]:
classifier = KNeighborsClassifier(n_neighbors = optimal_knn,n_jobs=5)
classifier.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=5, n_neighbors=3, p=2,
           weights='uniform')

### testing the model

In [16]:
y_pred = classifier.predict(X_test)

In [ ]:
?accuracy_score

### finding accuracy

In [17]:
acc = accuracy_score(Y_test, y_pred, normalize=True) * float(100)
acc


85.16666666666667